name: Publish Library

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version Name'
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build library
        run: ./gradlew :gsd:assembleRelease

      - name: Unit Test
        run: ./gradlew :gsd:test

      - name: Publish
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
        env:
          VERSION_NAME: ${{ github.event.inputs.versionName }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.GPG_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSWORD }}

      - name: Create and push tag
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag -a $TAG -m "Release $TAG"
          git push origin $TAG
        env:
          TAG: ${{ github.event.inputs.versionName }}

      - name: Create Release on GitHub
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.versionName }}
          name: ${{ github.event.inputs.versionName }}
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
